/* ClusteringPro — SVG illustrations (no image files: the app works offline).
   Colours come from CSS classes (art-*) so drawings follow the light/dark theme; fixed colours are
   used where the meaning is "cluster colour" (CL). Dendrograms are real: they are computed with the
   engine in hclust.js from small seeded datasets, so every tree on the home page is a true tree. */

const Art = {};
const CL = ['#4f46a5', '#e0803c', '#1fa39a', '#d64a6a', '#7bb041', '#8a5cd6', '#2b7bb9', '#c9a227'];
const F = 'font-family="Segoe UI, Helvetica, Arial, sans-serif"';

function txt(x, y, s, o) {
  o = o || {};
  return `<text x="${x}" y="${y}" ${F} font-size="${o.size || 10}" ${o.anchor ? `text-anchor="${o.anchor}"` : ''} ${o.bold ? 'font-weight="700"' : ''} ${o.fill ? `fill="${o.fill}"` : `class="${o.cls || 'art-txt'}"`} ${o.rot ? `transform="rotate(${o.rot} ${x} ${y})"` : ''} ${o.ls ? `letter-spacing="${o.ls}"` : ''} ${o.italic ? 'font-style="italic"' : ''}>${s}</text>`;
}
function blob(r, cx, cy, sd, n, sdy) { const P = []; for (let i = 0; i < n; i++) P.push([cx + randn(r) * sd, cy + randn(r) * (sdy || sd)]); return P; }
function pts(P, col, rad, o) { o = o || {}; return P.map(p => `<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="${rad || 3}" fill="${col}" ${o.stroke ? `stroke="${o.stroke}" stroke-width="${o.sw || 1}"` : ''} opacity="${o.op == null ? 0.92 : o.op}"/>`).join(''); }
function hullPath(P, col, pad, op) { return `<path d="${Geom.blobPath(Geom.hull(P), pad == null ? 9 : pad)}" fill="${col}" opacity="${op == null ? 0.16 : op}" stroke="${col}" stroke-width="1.2" stroke-opacity="0.55"/>`; }
function centroid(P) { return [P.reduce((a, p) => a + p[0], 0) / P.length, P.reduce((a, p) => a + p[1], 0) / P.length]; }
function star(x, y, r, col) { let d = ''; for (let i = 0; i < 8; i++) { const a = -Math.PI / 2 + i * Math.PI / 4, rr = i % 2 ? r * 0.45 : r; d += (i ? 'L' : 'M') + (x + rr * Math.cos(a)).toFixed(1) + ',' + (y + rr * Math.sin(a)).toFixed(1); } return `<path d="${d}Z" fill="${col}" stroke="#fff" stroke-width="1.3"/>`; }
function diamond(x, y, r, col) { return `<path d="M${x},${y - r} L${x + r},${y} L${x},${y + r} L${x - r},${y} Z" fill="${col}" stroke="#fff" stroke-width="1.3"/>`; }
function cardRect(x, y, w, h, o) { o = o || {}; return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${o.rx == null ? 10 : o.rx}" ${o.cls ? `class="${o.cls}"` : `fill="${o.fill || '#ffffff'}" ${o.stroke ? `stroke="${o.stroke}"` : ''}`} ${o.op ? `opacity="${o.op}"` : ''} ${o.filter ? `filter="${o.filter}"` : ''}/>`; }
function axes(x, y, w, h, o) { o = o || {}; return `<path d="M${x},${y} V${y + h} H${x + w}" class="art-ax" stroke-width="${o.sw || 1.2}"/>` + (o.xl ? txt(x + w / 2, y + h + 12, o.xl, { size: o.size || 8, anchor: 'middle', cls: 'art-mut' }) : '') + (o.yl ? txt(x - 6, y + h / 2, o.yl, { size: o.size || 8, anchor: 'middle', cls: 'art-mut', rot: -90 }) : ''); }

/* ---------- real dendrogram renderer ---------- */
Art.dendro = (hc, o) => {
  o = Object.assign({ x: 0, y: 0, w: 200, h: 100, k: 1, colors: CL, stroke: 2, neutral: '#9a9ab0', labels: null, labelSize: 8, cut: false, cutColor: '#d64a6a', orient: 'v', leafDot: 0, axis: false, cx: 0, cy: 0, R: 60, labelFill: null, curve: false }, o);
  const n = hc.n, L = HC.layout(hc);
  const maxH = (Math.max(...hc.height) || 1) * 1.06;
  const cl = HC.cutree(hc, o.k);
  const cmap = new Map(); hc.order.forEach(obs => { if (!cmap.has(cl[obs])) cmap.set(cl[obs], cmap.size); });
  const colOf = c => o.colors[cmap.get(c) % o.colors.length];
  const ang = u => u * 2 * Math.PI - Math.PI / 2;
  const map = (u, h) => {
    if (o.orient === 'v') return [o.x + u * o.w, o.y + o.h - h / maxH * o.h];
    if (o.orient === 'h') return [o.x + o.w - h / maxH * o.w, o.y + u * o.h];
    if (o.orient === 'hl') return [o.x + h / maxH * o.w, o.y + u * o.h];
    const r = o.R * (1 - h / maxH), a = ang(u); return [o.cx + r * Math.cos(a), o.cy + r * Math.sin(a)];
  };
  const P = (p) => `${p[0].toFixed(1)},${p[1].toFixed(1)}`;
  const across = (u1, u2, h) => {
    if (o.orient !== 'radial') return ` L${P(map(u2, h))}`;
    const r = o.R * (1 - h / maxH), a1 = ang(u1), a2 = ang(u2);
    return ` A${r.toFixed(1)} ${r.toFixed(1)} 0 ${a2 - a1 > Math.PI ? 1 : 0} 1 ${P(map(u2, h))}`;
  };
  const posOf = v => v < 0 ? [(L.leafX[-v - 1] + 0.5) / n, 0] : [(L.nodes[v - 1].x + 0.5) / n, L.nodes[v - 1].y];
  let paths = '';
  L.nodes.forEach(nd => {
    const same = nd.members.every(m => cl[m] === cl[nd.members[0]]);
    const col = same ? colOf(cl[nd.members[0]]) : o.neutral;
    let [ul, hl] = posOf(nd.l), [ur, hr] = posOf(nd.r);
    if (ul > ur) { [ul, ur] = [ur, ul]; [hl, hr] = [hr, hl]; }
    const d = `M${P(map(ul, hl))} L${P(map(ul, nd.y))}${across(ul, ur, nd.y)} L${P(map(ur, hr))}`;
    paths += `<path d="${d}" fill="none" stroke="${col}" stroke-width="${o.stroke}" stroke-linecap="round" stroke-linejoin="round"/>`;
  });
  let extra = '';
  if (o.leafDot) for (let i = 0; i < n; i++) { const p = map((L.leafX[i] + 0.5) / n, 0); extra += `<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="${o.leafDot}" fill="${colOf(cl[i])}" stroke="#fff" stroke-width="0.8"/>`; }
  if (o.labels) for (let i = 0; i < n; i++) {
    const u = (L.leafX[i] + 0.5) / n, p = map(u, 0), lab = o.labels[i] == null ? String(i + 1) : o.labels[i];
    const fill = o.labelFill ? colOf(cl[i]) : null;
    if (o.orient === 'v') extra += txt(p[0], p[1] + 4, lab, { size: o.labelSize, anchor: 'end', rot: -90, fill, cls: 'art-txt' }).replace(`y="${p[1] + 4}"`, `y="${(p[1] + 4).toFixed(1)}" dy="0.35em"`);
    else if (o.orient === 'h') extra += txt(p[0] + 4, p[1], lab, { size: o.labelSize, fill }).replace('<text ', '<text dy="0.35em" ');
    else if (o.orient === 'hl') extra += txt(p[0] - 4, p[1], lab, { size: o.labelSize, anchor: 'end', fill }).replace('<text ', '<text dy="0.35em" ');
    else {
      const a = ang(u), deg = a * 180 / Math.PI, flip = Math.cos(a) < 0, rr = o.R + 4;
      const x = o.cx + rr * Math.cos(a), y = o.cy + rr * Math.sin(a);
      extra += `<text x="${x.toFixed(1)}" y="${y.toFixed(1)}" ${F} font-size="${o.labelSize}" dy="0.35em" text-anchor="${flip ? 'end' : 'start'}" ${fill ? `fill="${fill}"` : 'class="art-txt"'} transform="rotate(${(flip ? deg + 180 : deg).toFixed(1)} ${x.toFixed(1)} ${y.toFixed(1)})">${lab}</text>`;
    }
  }
  if (o.cut && o.k > 1 && o.k <= n) {
    const hs = hc.height.slice().sort((a, b) => a - b), hcut = (hs[n - o.k - 1] + hs[n - o.k]) / 2;
    if (o.orient === 'radial') { const r = o.R * (1 - hcut / maxH); extra += `<circle cx="${o.cx}" cy="${o.cy}" r="${r.toFixed(1)}" fill="none" stroke="${o.cutColor}" stroke-width="1.2" stroke-dasharray="4 3"/>`; }
    else { const a = map(0, hcut), b = map(1, hcut); extra += `<line x1="${a[0].toFixed(1)}" y1="${a[1].toFixed(1)}" x2="${b[0].toFixed(1)}" y2="${b[1].toFixed(1)}" stroke="${o.cutColor}" stroke-width="1.2" stroke-dasharray="4 3"/>`; }
  }
  if (o.axis && o.orient === 'v') {
    const ax = o.x - 6; extra += `<line x1="${ax}" x2="${ax}" y1="${o.y}" y2="${o.y + o.h}" class="art-ax" stroke-width="1"/>`;
    for (let t = 0; t <= 4; t++) { const y = o.y + o.h - t / 4 * o.h; extra += `<line x1="${ax - 3}" x2="${ax}" y1="${y.toFixed(1)}" y2="${y.toFixed(1)}" class="art-ax"/>`; }
  }
  return paths + extra;
};

/* small seeded datasets that give nice trees */
function demoPoints(seed, groups, per, sd) {
  const r = rng(seed); let P = [];
  groups.forEach(g => P = P.concat(blob(r, g[0], g[1], sd || 9, per)));
  return P;
}
function demoTree(seed, groups, per, method, sd) { const P = demoPoints(seed, groups, per, sd); return { P, hc: HC.agglomerate(HC.dist(P), method || 'ward.D2') }; }

/* ================= brand mark ================= */
Art.logo = () => `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
  <rect x="2" y="2" width="36" height="36" rx="9" class="art-p"/>
  <g stroke="#ffffff" stroke-width="2.2" fill="none" stroke-linecap="round" opacity="0.95">
    <path d="M10 30 V22 H16 V30 M16 22 V15 H24 V22 M24 22 V30 H30 V22"/>
    <path d="M13 30 V26 M27 30 V26"/>
  </g>
  <circle cx="10" cy="31" r="2.6" fill="#e0803c"/><circle cx="16" cy="31" r="2.6" fill="#e0803c"/>
  <circle cx="24" cy="31" r="2.6" fill="#3fc4ba"/><circle cx="30" cy="31" r="2.6" fill="#3fc4ba"/>
  <circle cx="20" cy="11" r="3" fill="#ffffff"/>
</svg>`;

/* ================= hero ================= */
Art.hero = () => {
  const r = rng(11);
  const A = blob(r, 120, 160, 20, 20), B = blob(r, 250, 120, 19, 18), C = blob(r, 200, 285, 21, 20);
  const groups = [A, B, C];
  let scatter = '';
  groups.forEach((G, i) => { scatter += hullPath(G, CL[i]); });
  groups.forEach((G, i) => { scatter += pts(G, CL[i], 3.4, { stroke: '#fff', sw: 0.8 }); });
  groups.forEach((G, i) => { const c = centroid(G); scatter += star(c[0], c[1], 9, CL[i]); });
  const { hc } = demoTree(5, [[0, 0], [30, 4], [15, 30], [36, 28]], 4, 'ward.D2', 5);
  const dend = Art.dendro(hc, { x: 384, y: 74, w: 186, h: 96, k: 4, stroke: 2.2, cut: true, leafDot: 2.4, neutral: '#a4a4b8' });
  const { hc: hc2 } = demoTree(9, [[0, 0], [24, 0], [12, 22], [30, 26], [-6, 22]], 4, 'average', 5);
  const radial = Art.dendro(hc2, { orient: 'radial', cx: 430, cy: 300, R: 52, k: 5, stroke: 1.8, neutral: '#a4a4b8', leafDot: 2 });
  const sil = [0.82, 0.78, 0.74, 0.71, 0.66, 0.58, 0.3, 0.86, 0.8, 0.75, 0.7, 0.62, 0.5, 0.79, 0.76, 0.68, 0.6, 0.45];
  const silCol = i => i < 7 ? CL[0] : i < 13 ? CL[1] : CL[2];
  let bars = ''; sil.forEach((s, i) => { bars += `<rect x="500" y="${252 + i * 6.4}" width="${(s * 66).toFixed(1)}" height="5.2" rx="1.2" fill="${silCol(i)}" opacity="0.9"/>`; });
  return `<svg viewBox="0 0 600 400" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cluster plot, dendrogram, radial tree and silhouette plot">
  <defs>
    <linearGradient id="hg" x1="0" x2="1" y1="0" y2="1"><stop offset="0" stop-color="#e9e6fb"/><stop offset="0.55" stop-color="#e2f3f2"/><stop offset="1" stop-color="#fbe9dc"/></linearGradient>
    <filter id="sh" x="-10%" y="-10%" width="130%" height="140%"><feDropShadow dx="0" dy="6" stdDeviation="8" flood-color="#241f5a" flood-opacity="0.16"/></filter>
    <pattern id="dots" width="14" height="14" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="#4f46a5" opacity="0.18"/></pattern>
  </defs>
  <rect x="0" y="0" width="600" height="400" rx="18" fill="url(#hg)"/>
  <rect x="0" y="0" width="600" height="400" rx="18" fill="url(#dots)"/>
  ${cardRect(28, 44, 336, 322, { filter: 'url(#sh)', op: 0.96 })}
  ${txt(44, 66, 'K-MEANS · k = 3 · AVERAGE SILHOUETTE 0.71', { size: 9.5, bold: true, fill: '#2b2b40', ls: 1.2 })}
  ${axes(60, 84, 290, 262, { xl: 'Dim 1 (48.2 %)', yl: 'Dim 2 (27.9 %)', size: 8.5 })}
  ${scatter}
  ${cardRect(372, 44, 208, 156, { filter: 'url(#sh)', op: 0.96 })}
  ${txt(384, 62, 'WARD.D2 · 4 CLUSTERS', { size: 9, bold: true, fill: '#2b2b40', ls: 1.2 })}
  ${dend}
  ${txt(566, 184, 'cut', { size: 8, anchor: 'end', fill: '#d64a6a', italic: true })}
  ${cardRect(372, 214, 116, 152, { filter: 'url(#sh)', op: 0.96 })}
  ${txt(384, 232, 'RADIAL · UPGMA', { size: 8.5, bold: true, fill: '#2b2b40', ls: 1 })}
  ${radial}
  ${cardRect(496, 214, 84, 152, { filter: 'url(#sh)', op: 0.96 })}
  ${txt(500, 232, 'SILHOUETTE', { size: 8.5, bold: true, fill: '#2b2b40', ls: 1 })}
  ${txt(500, 245, 's(i)', { size: 7.5, fill: '#777' })}
  ${bars}
  <line x1="500" x2="566" y1="${252 + sil.length * 6.4 + 2}" y2="${252 + sil.length * 6.4 + 2}" stroke="#bbb" stroke-width="0.8"/>
</svg>`;
};

/* ================= block feature thumbnails (200 × 110) ================= */
Art.block = n => {
  const V = '<svg viewBox="0 0 200 110" xmlns="http://www.w3.org/2000/svg">';
  switch (n) {
    case 2: return `${V}
      <rect x="22" y="14" width="120" height="82" rx="8" class="art-card"/>
      ${[0, 1, 2, 3, 4].map(i => `<rect x="30" y="${22 + i * 14}" width="104" height="10" rx="2" fill="${CL[0]}" opacity="${i === 0 ? 0.85 : 0.13}"/>`).join('')}
      ${[0, 1, 2].map(j => `<line x1="${58 + j * 26}" x2="${58 + j * 26}" y1="22" y2="90" class="art-line" stroke-width="1" opacity="0.5"/>`).join('')}
      ${[[150, 24, CL[6], '1.5'], [150, 42, CL[1], 'A/B'], [150, 60, CL[2], '0/1'], [150, 78, CL[3], 'n']].map(([x, y, c, l]) => `<rect x="${x}" y="${y}" width="36" height="14" rx="7" fill="${c}" opacity="0.9"/>${txt(x + 18, y + 10, l, { size: 8, anchor: 'middle', bold: true, fill: '#fff' })}`).join('')}
    </svg>`;
    case 3: { let cells = ''; const k = 7; for (let i = 0; i < k; i++) for (let j = 0; j < k; j++) { const d = Math.abs(i - j) + ((i < 3) === (j < 3) ? 0 : 3); const t = Math.min(1, d / 8); cells += `<rect x="${44 + j * 16}" y="${4 + i * 12.5}" width="15" height="11.5" fill="${CL[0]}" opacity="${(0.95 - t * 0.85).toFixed(2)}"/>`; } return `${V}${cells}${txt(100, 105, 'distance matrix', { size: 8, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 4: { const { hc } = demoTree(21, [[0, 0], [22, 2], [10, 20]], 4, 'average', 4); return `${V}${Art.dendro(hc, { x: 20, y: 12, w: 160, h: 80, k: 3, stroke: 2.4, cut: true, leafDot: 2.5 })}</svg>`; }
    case 5: { const r = rng(4); const G = [blob(r, 60, 45, 12, 12), blob(r, 130, 40, 11, 12), blob(r, 100, 82, 10, 12)]; return `${V}${G.map((g, i) => hullPath(g, CL[i], 7)).join('')}${G.map((g, i) => pts(g, CL[i], 3)).join('')}${G.map((g, i) => { const c = centroid(g); return star(c[0], c[1], 7, CL[i]); }).join('')}</svg>`; }
    case 6: { const wss = [100, 52, 28, 22, 19, 17, 15.5], sx = i => 30 + i * 22, sy = v => 92 - v * 0.75; return `${V}${axes(24, 14, 150, 80)}<path d="${wss.map((v, i) => (i ? 'L' : 'M') + sx(i) + ',' + sy(v)).join(' ')}" fill="none" stroke="${CL[0]}" stroke-width="2.4"/>${wss.map((v, i) => `<circle cx="${sx(i)}" cy="${sy(v)}" r="3.2" fill="${i === 2 ? CL[1] : CL[0]}"/>`).join('')}<circle cx="${sx(2)}" cy="${sy(28)}" r="8" fill="none" stroke="${CL[1]}" stroke-width="1.6" stroke-dasharray="3 2"/>${txt(sx(2) + 12, sy(28) - 8, 'k = 3', { size: 9, bold: true, fill: CL[1] })}${txt(100, 104, 'elbow · silhouette · gap', { size: 8, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 7: { let g = ''; const vals = [[0.9, 0.2, 0.5, 0.1], [0.3, 0.8, 0.2, 0.6], [0.1, 0.4, 0.9, 0.7]]; vals.forEach((row, i) => row.forEach((v, j) => { g += `<rect x="${56 + j * 24}" y="${20 + i * 22}" width="22" height="20" rx="3" fill="${CL[i]}" opacity="${(0.15 + v * 0.8).toFixed(2)}"/>`; })); return `${V}${g}${[0, 1, 2].map(i => `<circle cx="44" cy="${30 + i * 22}" r="5" fill="${CL[i]}"/>`).join('')}${['V1', 'V2', 'V3', 'V4'].map((l, j) => txt(67 + j * 24, 98, l, { size: 8, anchor: 'middle', cls: 'art-mut' })).join('')}</svg>`; }
    case 8: return `${V}
      <rect x="30" y="18" width="90" height="70" rx="6" class="art-card"/><path d="M36 82 L60 52 L78 68 L96 40 L114 82 Z" fill="${CL[0]}" opacity="0.8"/><circle cx="100" cy="34" r="7" fill="${CL[1]}"/>
      <g ${F} font-size="9" font-weight="700"><rect x="132" y="22" width="44" height="16" rx="4" fill="${CL[6]}"/><text x="154" y="33" text-anchor="middle" fill="#fff">PNG 600</text>
      <rect x="132" y="44" width="44" height="16" rx="4" fill="${CL[0]}"/><text x="154" y="55" text-anchor="middle" fill="#fff">TIFF</text>
      <rect x="132" y="66" width="44" height="16" rx="4" fill="${CL[1]}"/><text x="154" y="77" text-anchor="middle" fill="#fff">SVG</text></g>
    </svg>`;
    default: { const r = rng(2); const G = [blob(r, 55, 50, 12, 14), blob(r, 140, 45, 12, 14), blob(r, 100, 85, 9, 12)]; return `${V}${G.map((g, i) => pts(g, CL[i], 3.2)).join('')}</svg>`; }
  }
};

/* ================= method gallery cards (220 × 128) ================= */
Art.method = id => {
  const V = '<svg viewBox="0 0 220 128" xmlns="http://www.w3.org/2000/svg">';
  const arrow = (x1, y1, x2, y2, col) => `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${col || '#888'}" stroke-width="1.6" marker-end="url(#ah)"/>`;
  const defs = `<defs><marker id="ah" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7 Z" fill="#888"/></marker></defs>`;
  switch (id) {
    case 'agnes': { const { hc } = demoTree(31, [[0, 0], [20, 3], [10, 18], [28, 20]], 3, 'average', 4); return `${V}${defs}${Art.dendro(hc, { x: 30, y: 14, w: 150, h: 84, k: 4, stroke: 2.2, leafDot: 2.6 })}${arrow(200, 104, 200, 26, CL[0])}${txt(206, 66, 'merge', { size: 8, cls: 'art-mut', rot: -90 })}</svg>`; }
    case 'diana': { const { hc } = demoTree(32, [[0, 0], [20, 3], [10, 18], [28, 20]], 3, 'complete', 4); return `${V}${defs}${Art.dendro(hc, { x: 30, y: 14, w: 150, h: 84, k: 4, stroke: 2.2, leafDot: 2.6 })}${arrow(200, 22, 200, 100, CL[1])}${txt(206, 66, 'split', { size: 8, cls: 'art-mut', rot: -90 })}</svg>`; }
    case 'kmeans': { const r = rng(41); const G = [blob(r, 60, 50, 13, 14), blob(r, 150, 44, 12, 14), blob(r, 110, 92, 11, 14)]; return `${V}${defs}${G.map((g, i) => hullPath(g, CL[i], 7)).join('')}${G.map((g, i) => pts(g, CL[i], 3)).join('')}${G.map((g, i) => { const c = centroid(g); return `${arrow(c[0] + 22, c[1] - 18, c[0] + 5, c[1] - 4)}${star(c[0], c[1], 8, CL[i])}`; }).join('')}</svg>`; }
    case 'pam': { const r = rng(42); const G = [blob(r, 60, 50, 13, 14), blob(r, 150, 44, 12, 14), blob(r, 110, 92, 11, 14)]; return `${V}${G.map((g, i) => hullPath(g, CL[i], 7)).join('')}${G.map((g, i) => pts(g, CL[i], 3)).join('')}${G.map((g, i) => { const c = centroid(g); let best = g[0], bd = Infinity; g.forEach(p => { const d = KM.sqd(p, c); if (d < bd) { bd = d; best = p; } }); return `<circle cx="${best[0].toFixed(1)}" cy="${best[1].toFixed(1)}" r="7" fill="none" stroke="${CL[i]}" stroke-width="2.4"/><circle cx="${best[0].toFixed(1)}" cy="${best[1].toFixed(1)}" r="3.4" fill="${CL[i]}" stroke="#fff" stroke-width="1"/>`; }).join('')}${txt(110, 122, 'medoids are real observations', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 'clara': { const r = rng(43); let g = ''; for (let s = 0; s < 3; s++) { const ox = 20 + s * 66; g += `<rect x="${ox}" y="24" width="56" height="70" rx="6" class="art-card"/>`; const P = blob(r, ox + 20, 48, 7, 6).concat(blob(r, ox + 38, 72, 7, 6)); g += pts(P.slice(0, 6), CL[0], 2.4) + pts(P.slice(6), CL[1], 2.4); g += txt(ox + 28, 108, `sample ${s + 1}`, { size: 7.5, anchor: 'middle', cls: 'art-mut' }); } return `${V}${g}${txt(110, 16, 'PAM on repeated samples → best medoids', { size: 8, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 'fuzzy': { const r = rng(44); const A = blob(r, 70, 62, 16, 16), B = blob(r, 150, 62, 16, 16); const mix = p => { const da = Math.hypot(p[0] - 70, p[1] - 62), db = Math.hypot(p[0] - 150, p[1] - 62); return da / (da + db); }; const col = (t) => { const a = [79, 70, 165], b = [224, 128, 60]; return `rgb(${a.map((v, i) => Math.round(v * (1 - t) + b[i] * t)).join(',')})`; }; return `${V}${A.concat(B).map(p => `<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="3.4" fill="${col(mix(p))}"/>`).join('')}<defs><linearGradient id="fz" x1="0" x2="1"><stop offset="0" stop-color="${CL[0]}"/><stop offset="1" stop-color="${CL[1]}"/></linearGradient></defs><rect x="60" y="108" width="100" height="6" rx="3" fill="url(#fz)"/>${txt(58, 113, 'u = 1', { size: 7, anchor: 'end', cls: 'art-mut' })}${txt(162, 113, 'u = 0', { size: 7, cls: 'art-mut' })}</svg>`; }
    case 'gmm': { const r = rng(45); const A = blob(r, 70, 60, 14, 14, 8), B = blob(r, 140, 70, 9, 14, 18); return `${V}<ellipse cx="70" cy="60" rx="34" ry="19" fill="${CL[0]}" opacity="0.13" stroke="${CL[0]}" stroke-width="1.2"/><ellipse cx="70" cy="60" rx="18" ry="10" fill="none" stroke="${CL[0]}" stroke-width="1" opacity="0.6"/><ellipse cx="140" cy="70" rx="22" ry="42" fill="${CL[2]}" opacity="0.13" stroke="${CL[2]}" stroke-width="1.2" transform="rotate(20 140 70)"/><ellipse cx="140" cy="70" rx="11" ry="21" fill="none" stroke="${CL[2]}" stroke-width="1" opacity="0.6" transform="rotate(20 140 70)"/>${pts(A, CL[0], 2.8)}${pts(B.map(p => [140 + (p[0] - 140) * Math.cos(0.35) - (p[1] - 70) * Math.sin(0.35), 70 + (p[0] - 140) * Math.sin(0.35) + (p[1] - 70) * Math.cos(0.35)]), CL[2], 2.8)}${txt(110, 122, 'Gaussian mixture · BIC picks the model', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 'dbscan': { const r = rng(46); const ring = []; for (let i = 0; i < 40; i++) { const a = i / 40 * 2 * Math.PI; ring.push([110 + 42 * Math.cos(a) + randn(r) * 2.5, 62 + 40 * Math.sin(a) + randn(r) * 2.5]); } const core = blob(r, 110, 62, 7, 18); const noise = [[20, 20], [200, 110], [24, 108], [196, 18], [60, 118]]; return `${V}${pts(ring, CL[0], 3)}${pts(core, CL[1], 3)}${noise.map(p => `<path d="M${p[0] - 3},${p[1] - 3} L${p[0] + 3},${p[1] + 3} M${p[0] - 3},${p[1] + 3} L${p[0] + 3},${p[1] - 3}" stroke="#999" stroke-width="1.6"/>`).join('')}<circle cx="${ring[5][0].toFixed(1)}" cy="${ring[5][1].toFixed(1)}" r="11" fill="none" stroke="${CL[3]}" stroke-width="1.2" stroke-dasharray="3 2"/>${txt(ring[5][0] + 14, ring[5][1] - 8, 'ε', { size: 9, fill: CL[3], bold: true })}</svg>`; }
    case 'hkmeans': { const { hc } = demoTree(47, [[0, 0], [20, 3], [10, 18]], 3, 'ward.D2', 4); return `${V}${defs}${Art.dendro(hc, { x: 14, y: 16, w: 96, h: 80, k: 3, stroke: 2, leafDot: 2.2 })}${arrow(116, 58, 134, 58)}${[[160, 40], [190, 46], [175, 82]].map((c, i) => `<circle cx="${c[0]}" cy="${c[1]}" r="13" fill="${CL[i]}" opacity="0.18"/>${star(c[0], c[1], 6, CL[i])}`).join('')}${txt(110, 122, 'tree gives the starting centres', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 'tanglegram': { const { hc } = demoTree(48, [[0, 0], [22, 2], [10, 20]], 3, 'average', 4); const hc2 = HC.agglomerate(HC.dist(demoPoints(48, [[0, 0], [22, 2], [10, 20]], 3, 4)), 'single'); const n = hc.n; const L1 = HC.layout(hc), L2 = HC.layout(hc2); const cl = HC.cutree(hc, 3); let lines = ''; for (let i = 0; i < n; i++) { const y1 = 12 + (L1.leafX[i] + 0.5) / n * 100, y2 = 12 + (L2.leafX[i] + 0.5) / n * 100; lines += `<line x1="92" y1="${y1.toFixed(1)}" x2="128" y2="${y2.toFixed(1)}" stroke="${CL[(cl[i] - 1) % CL.length]}" stroke-width="1.4" opacity="0.8"/>`; } return `${V}${Art.dendro(hc, { orient: 'hl', x: 14, y: 12, w: 74, h: 100, k: 3, stroke: 1.8 })}${Art.dendro(hc2, { orient: 'h', x: 132, y: 12, w: 74, h: 100, k: 3, stroke: 1.8 })}${lines}${txt(110, 124, 'UPGMA vs single · entanglement', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 'heatmap': { const { hc } = demoTree(49, [[0, 0], [20, 3], [10, 18]], 3, 'average', 4); const n = hc.n; const cols = 8; let cells = ''; const cl = HC.cutree(hc, 3); hc.order.forEach((obs, i) => { for (let j = 0; j < cols; j++) { const v = (cl[obs] === 1 ? [0.9, 0.8, 0.7, 0.2, 0.1, 0.3, 0.2, 0.1] : cl[obs] === 2 ? [0.1, 0.2, 0.3, 0.9, 0.8, 0.7, 0.2, 0.1] : [0.2, 0.1, 0.2, 0.2, 0.3, 0.2, 0.9, 0.8])[j] + (Math.sin(obs * 7 + j) * 0.12); cells += `<rect x="${62 + j * 15}" y="${(14 + i * 100 / n).toFixed(1)}" width="14.5" height="${(100 / n - 0.6).toFixed(1)}" fill="${v > 0.5 ? CL[3] : CL[6]}" opacity="${Math.abs(v - 0.5) * 1.6 + 0.15}"/>`; } }); return `${V}${Art.dendro(hc, { orient: 'hl', x: 10, y: 14, w: 46, h: 100, k: 3, stroke: 1.6 })}${cells}${txt(194, 64, 'variables', { size: 7.5, cls: 'art-mut', rot: 90 })}</svg>`; }
    case 'validation': { const sil = [0.85, 0.8, 0.76, 0.7, 0.62, 0.4, 0.15, 0.88, 0.83, 0.78, 0.72, 0.66, 0.5, 0.82, 0.77, 0.7, 0.6, 0.35, -0.1]; return `${V}${sil.map((s, i) => `<rect x="${s >= 0 ? 60 : 60 + s * 100}" y="${10 + i * 5.6}" width="${(Math.abs(s) * 100).toFixed(1)}" height="4.6" fill="${i < 7 ? CL[0] : i < 13 ? CL[1] : CL[2]}"/>`).join('')}<line x1="60" x2="60" y1="8" y2="118" class="art-ax"/><line x1="${60 + 0.66 * 100}" x2="${60 + 0.66 * 100}" y1="8" y2="118" stroke="${CL[3]}" stroke-dasharray="3 2" stroke-width="1.2"/>${txt(60 + 66 + 3, 118, 'mean 0.66', { size: 7.5, fill: CL[3] })}${txt(10, 66, 'silhouette', { size: 8, cls: 'art-mut', rot: -90, anchor: 'middle' })}</svg>`; }
    case 'tendency': { const r = rng(50); const U = []; for (let i = 0; i < 50; i++) U.push([14 + r() * 84, 14 + r() * 90]); const Cc = blob(r, 140, 40, 9, 16).concat(blob(r, 186, 90, 9, 16)).concat(blob(r, 140, 96, 8, 14)); return `${V}<rect x="10" y="10" width="92" height="98" rx="6" class="art-card"/><rect x="118" y="10" width="92" height="98" rx="6" class="art-card"/>${pts(U, '#999', 2.4)}${pts(Cc, CL[0], 2.4)}${txt(56, 122, 'H ≈ 0.5 · no structure', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}${txt(164, 122, 'H ≈ 0.9 · clusterable', { size: 7.5, anchor: 'middle', fill: CL[0] })}</svg>`; }
    case 'optk': { const gap = [0.20, 0.42, 0.66, 0.62, 0.60, 0.61, 0.58], sx = i => 34 + i * 26, sy = v => 100 - v * 110; return `${V}${axes(28, 12, 176, 92, { xl: 'number of clusters k', size: 8 })}${gap.map((v, i) => `<line x1="${sx(i)}" x2="${sx(i)}" y1="${sy(v + 0.05)}" y2="${sy(v - 0.05)}" stroke="${CL[0]}" stroke-width="1.2"/>`).join('')}<path d="${gap.map((v, i) => (i ? 'L' : 'M') + sx(i) + ',' + sy(v)).join(' ')}" fill="none" stroke="${CL[0]}" stroke-width="2"/>${gap.map((v, i) => `<circle cx="${sx(i)}" cy="${sy(v)}" r="3" fill="${i === 2 ? CL[1] : CL[0]}"/>`).join('')}<line x1="${sx(2)}" x2="${sx(2)}" y1="16" y2="104" stroke="${CL[1]}" stroke-dasharray="3 2"/>${txt(sx(2) + 5, 24, 'k = 3', { size: 9, bold: true, fill: CL[1] })}${txt(22, 58, 'gap', { size: 8, cls: 'art-mut', rot: -90, anchor: 'middle' })}</svg>`; }
    case 'supervised': { const r = rng(51); const G = [blob(r, 62, 60, 13, 14), blob(r, 150, 62, 13, 14)]; return `${V}${G.map((g, i) => pts(g, CL[i], 3)).join('')}<line x1="106" y1="10" x2="106" y2="114" stroke="${CL[3]}" stroke-width="2" stroke-dasharray="5 3"/>${txt(106, 124, 'LDA boundary · new cases assigned', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}<circle cx="96" cy="40" r="5" fill="none" stroke="${CL[0]}" stroke-width="2"/>${txt(96, 32, '?', { size: 9, anchor: 'middle', bold: true, fill: CL[0] })}<circle cx="118" cy="84" r="5" fill="none" stroke="${CL[1]}" stroke-width="2"/>${txt(118, 100, '?', { size: 9, anchor: 'middle', bold: true, fill: CL[1] })}</svg>`; }
    default: return `${V}</svg>`;
  }
};

/* ================= data-type icons (200 × 64) ================= */
Art.dtype = id => {
  const V = '<svg viewBox="0 0 200 64" xmlns="http://www.w3.org/2000/svg">';
  switch (id) {
    case 'quant': return `${V}${[8, 16, 28, 44, 52, 40, 26, 14, 8].map((h, i) => `<rect x="${40 + i * 14}" y="${56 - h}" width="11" height="${h}" rx="2" fill="${CL[0]}" opacity="${0.5 + i * 0.05}"/>`).join('')}<path d="M40 52 C 70 50, 90 6, 110 6 C 130 6, 150 50, 168 54" fill="none" stroke="${CL[1]}" stroke-width="2"/></svg>`;
    case 'binary': { let g = ''; const bits = [[1, 0, 1, 1, 0, 1, 0, 0], [0, 1, 1, 0, 1, 0, 1, 1], [1, 1, 0, 0, 1, 1, 0, 1]]; bits.forEach((row, i) => row.forEach((b, j) => { g += `<rect x="${36 + j * 17}" y="${8 + i * 16}" width="15" height="14" rx="3" fill="${b ? CL[0] : '#bbb'}" opacity="${b ? 0.9 : 0.35}"/>${txt(43.5 + j * 17, 19 + i * 16, b, { size: 9, anchor: 'middle', bold: true, fill: '#fff' })}`; })); return `${V}${g}</svg>`; }
    case 'nominal': return `${V}${['#4f46a5', '#e0803c', '#1fa39a', '#d64a6a', '#7bb041'].map((c, i) => `<rect x="${30 + i * 30}" y="14" width="24" height="36" rx="6" fill="${c}" opacity="0.85"/>${txt(42 + i * 30, 36, 'ABCDE'[i], { size: 12, anchor: 'middle', bold: true, fill: '#fff' })}`).join('')}</svg>`;
    case 'ordinal': return `${V}${[0, 1, 2, 3, 4].map(i => `<rect x="${34 + i * 28}" y="${50 - (i + 1) * 8}" width="22" height="${(i + 1) * 8}" rx="3" fill="${CL[2]}" opacity="${0.4 + i * 0.14}"/>`).join('')}${txt(45, 60, 'low', { size: 8, anchor: 'middle', cls: 'art-mut' })}${txt(157, 60, 'high', { size: 8, anchor: 'middle', cls: 'art-mut' })}<path d="M60 8 H150" stroke="#999" stroke-width="1.2" marker-end="url(#ah2)"/><defs><marker id="ah2" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7 Z" fill="#999"/></marker></defs></svg>`;
    case 'count': { const r = rng(61); let g = ''; for (let i = 0; i < 4; i++) for (let j = 0; j < 6; j++) { const v = r(); g += v < 0.35 ? '' : `<circle cx="${44 + j * 22}" cy="${9 + i * 11.5}" r="${(v * 5.5).toFixed(1)}" fill="${CL[4]}" opacity="0.8"/>`; } return `${V}${g}${txt(18, 28, 'sites', { size: 7.5, cls: 'art-mut', rot: -90, anchor: 'middle' })}${txt(100, 62, 'species abundance', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 'mixed': return `${V}<rect x="30" y="12" width="40" height="40" rx="6" fill="${CL[0]}" opacity="0.85"/>${txt(50, 37, '1.5', { size: 11, anchor: 'middle', bold: true, fill: '#fff' })}<rect x="80" y="12" width="40" height="40" rx="6" fill="${CL[1]}" opacity="0.85"/>${txt(100, 37, 'A/B', { size: 11, anchor: 'middle', bold: true, fill: '#fff' })}<rect x="130" y="12" width="40" height="40" rx="6" fill="${CL[2]}" opacity="0.85"/>${txt(150, 37, '0/1', { size: 11, anchor: 'middle', bold: true, fill: '#fff' })}</svg>`;
    case 'dist': { let g = ''; for (let i = 0; i < 6; i++) for (let j = 0; j <= i; j++) g += `<rect x="${52 + j * 16}" y="${6 + i * 9}" width="15" height="8" fill="${CL[6]}" opacity="${(0.2 + Math.abs(i - j) / 6 * 0.75).toFixed(2)}"/>`; return `${V}${g}${txt(160, 34, 'D', { size: 16, anchor: 'middle', bold: true, fill: CL[6] })}</svg>`; }
    default: return `${V}</svg>`;
  }
};

/* ================= theory figures ================= */
Art.fig = id => {
  const W = 320, H = 190;
  const V = `<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg">`;
  const defs = `<defs><marker id="af" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7 Z" fill="#666"/></marker></defs>`;
  const arrow = (x1, y1, x2, y2, col, w) => `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${col || '#666'}" stroke-width="${w || 1.4}" marker-end="url(#af)"/>`;
  switch (id) {
    case 'whatis': { const r = rng(71); const G = [blob(r, 80, 70, 16, 18), blob(r, 220, 60, 15, 18), blob(r, 160, 140, 14, 18)]; const c = G.map(centroid); return `${V}${defs}${G.map((g, i) => hullPath(g, CL[i], 8)).join('')}${G.map((g, i) => pts(g, CL[i], 3.2)).join('')}${arrow(c[0][0] + 14, c[0][1], c[1][0] - 14, c[1][1] - 2, '#555')}${txt((c[0][0] + c[1][0]) / 2, c[0][1] - 8, 'between: large', { size: 9, anchor: 'middle', fill: '#555', bold: true })}<line x1="${G[2][0][0].toFixed(1)}" y1="${G[2][0][1].toFixed(1)}" x2="${G[2][5][0].toFixed(1)}" y2="${G[2][5][1].toFixed(1)}" stroke="${CL[2]}" stroke-width="1.6"/>${txt(c[2][0], c[2][1] + 34, 'within: small', { size: 9, anchor: 'middle', fill: CL[2], bold: true })}</svg>`; }
    case 'distance': { const a = [60, 140], b = [230, 50]; return `${V}${axes(30, 20, 270, 140, { xl: 'variable 1', yl: 'variable 2' })}<path d="M${a[0]},${a[1]} H${b[0]} V${b[1]}" fill="none" stroke="${CL[1]}" stroke-width="2.2" stroke-dasharray="6 3"/><line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${CL[0]}" stroke-width="2.4"/><path d="M${a[0]},${a[1]} H${b[0]}" fill="none" stroke="${CL[2]}" stroke-width="3" opacity="0.5"/><circle cx="${a[0]}" cy="${a[1]}" r="5" fill="#333"/><circle cx="${b[0]}" cy="${b[1]}" r="5" fill="#333"/>${txt(a[0] - 8, a[1] + 4, 'i', { size: 11, anchor: 'end', bold: true })}${txt(b[0] + 8, b[1] + 4, 'j', { size: 11, bold: true })}${txt(120, 86, 'Euclidean √Σ(xᵢ−xⱼ)²', { size: 9.5, fill: CL[0], bold: true, rot: -28 })}${txt(150, 156, 'Manhattan Σ|xᵢ−xⱼ|', { size: 9.5, fill: CL[1], bold: true, anchor: 'middle' })}${txt(150, 176, 'Chebyshev max|xᵢ−xⱼ|  (longest side only)', { size: 8.5, fill: CL[2], anchor: 'middle' })}</svg>`; }
    case 'scale': { const r = rng(72); const A = blob(r, 80, 60, 40, 20, 4), B = blob(r, 80, 120, 40, 20, 4); const C = blob(r, 230, 55, 16, 20, 16), D = blob(r, 230, 125, 16, 20, 16); return `${V}${txt(80, 16, 'raw units', { size: 9.5, anchor: 'middle', bold: true, cls: 'art-mut' })}${txt(230, 16, 'standardised', { size: 9.5, anchor: 'middle', bold: true, cls: 'art-mut' })}${axes(24, 24, 116, 150, { xl: 'yield (kg/ha, 0–8000)', yl: 'pH (5–8)', size: 7.5 })}${axes(170, 24, 120, 150, { xl: 'z(yield)', yl: 'z(pH)', size: 7.5 })}${pts(A, CL[0], 2.8)}${pts(B, CL[1], 2.8)}${pts(C, CL[0], 2.8)}${pts(D, CL[1], 2.8)}<line x1="${A[3][0]}" y1="${A[3][1]}" x2="${B[9][0]}" y2="${B[9][1]}" stroke="#555" stroke-dasharray="3 2"/><line x1="${A[3][0]}" y1="${A[3][1]}" x2="${A[15][0]}" y2="${A[15][1]}" stroke="${CL[3]}" stroke-width="2"/>${txt(80, 34, 'the pH difference is invisible', { size: 7.5, anchor: 'middle', fill: CL[3], bold: true })}</svg>`; }
    case 'binary': { const cell = (x, y, s, col) => `<rect x="${x}" y="${y}" width="60" height="34" fill="${col}" opacity="0.18" stroke="${col}"/>${txt(x + 30, y + 22, s, { size: 13, anchor: 'middle', bold: true, fill: col })}`; return `${V}${txt(130, 22, 'object j', { size: 10, anchor: 'middle', bold: true })}${txt(100, 40, '1', { size: 10, anchor: 'middle', cls: 'art-mut' })}${txt(160, 40, '0', { size: 10, anchor: 'middle', cls: 'art-mut' })}${txt(28, 80, 'object i', { size: 10, anchor: 'middle', bold: true, rot: -90 })}${txt(52, 66, '1', { size: 10, anchor: 'middle', cls: 'art-mut' })}${txt(52, 104, '0', { size: 10, anchor: 'middle', cls: 'art-mut' })}${cell(70, 46, 'a', CL[0])}${cell(130, 46, 'b', CL[1])}${cell(70, 84, 'c', CL[1])}${cell(130, 84, 'd', '#888')}${txt(210, 60, 'Jaccard = a / (a+b+c)', { size: 9.5, bold: true, fill: CL[0] })}${txt(210, 78, 'Dice = 2a / (2a+b+c)', { size: 9, fill: CL[0] })}${txt(210, 96, 'Simple matching', { size: 9, fill: '#666' })}${txt(210, 110, '= (a+d) / (a+b+c+d)', { size: 9, fill: '#666' })}${txt(160, 150, 'a = shared presences · d = shared absences', { size: 8.5, anchor: 'middle', cls: 'art-mut' })}${txt(160, 166, 'Ecology usually ignores d: two sites are not similar', { size: 8.5, anchor: 'middle', cls: 'art-mut' })}${txt(160, 180, 'because both lack a rare species.', { size: 8.5, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 'linkage': { const r = rng(73); const mk2 = (ox) => { const A = blob(r, ox + 22, 40, 8, 7), B = blob(r, ox + 74, 74, 8, 7); return { A, B }; }; const panels = ['single', 'complete', 'average', 'centroid', 'Ward']; let g = ''; panels.forEach((name, p) => { const ox = 6 + p * 62, oy = 0; const rr = rng(73); const A = blob(rr, ox + 22, oy + 40, 7, 7), B = blob(rr, ox + 52, oy + 66, 7, 7); g += `<rect x="${ox}" y="${oy + 14}" width="58" height="72" rx="6" class="art-card"/>`; g += pts(A, CL[0], 2.4) + pts(B, CL[1], 2.4); if (name === 'single') { let best = null, bd = Infinity; A.forEach(a => B.forEach(b => { const d = KM.sqd(a, b); if (d < bd) { bd = d; best = [a, b]; } })); g += `<line x1="${best[0][0]}" y1="${best[0][1]}" x2="${best[1][0]}" y2="${best[1][1]}" stroke="${CL[3]}" stroke-width="1.8"/>`; } else if (name === 'complete') { let best = null, bd = -1; A.forEach(a => B.forEach(b => { const d = KM.sqd(a, b); if (d > bd) { bd = d; best = [a, b]; } })); g += `<line x1="${best[0][0]}" y1="${best[0][1]}" x2="${best[1][0]}" y2="${best[1][1]}" stroke="${CL[3]}" stroke-width="1.8"/>`; } else if (name === 'average') { A.forEach(a => B.forEach(b => { g += `<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${CL[3]}" stroke-width="0.5" opacity="0.45"/>`; })); } else if (name === 'centroid') { const ca = centroid(A), cb = centroid(B); g += `<line x1="${ca[0]}" y1="${ca[1]}" x2="${cb[0]}" y2="${cb[1]}" stroke="${CL[3]}" stroke-width="1.8"/>` + diamond(ca[0], ca[1], 4, CL[0]) + diamond(cb[0], cb[1], 4, CL[1]); } else { const c = centroid(A.concat(B)); A.concat(B).forEach(p => { g += `<line x1="${p[0]}" y1="${p[1]}" x2="${c[0]}" y2="${c[1]}" stroke="${CL[3]}" stroke-width="0.7" opacity="0.6"/>`; }); g += diamond(c[0], c[1], 4, CL[3]); } g += txt(ox + 29, oy + 98, name, { size: 8.5, anchor: 'middle', bold: true }); }); g += txt(14, 122, 'single: nearest pair of members', { size: 8, cls: 'art-mut' }) + txt(14, 135, 'complete: farthest pair', { size: 8, cls: 'art-mut' }) + txt(14, 148, 'average (UPGMA): mean of all pairs', { size: 8, cls: 'art-mut' }) + txt(170, 122, 'centroid: distance between centres', { size: 8, cls: 'art-mut' }) + txt(170, 135, 'Ward: increase in within-group variance', { size: 8, cls: 'art-mut' }) + txt(160, 172, 'the same two groups; the red mark shows what each rule measures', { size: 8, anchor: 'middle', cls: 'art-mut', italic: true }); return `${V}${g}</svg>`; }
    case 'dendrogram': { const { hc } = demoTree(74, [[0, 0], [18, 2], [9, 16]], 3, 'average', 3.5); const labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']; return `${V}${defs}${Art.dendro(hc, { x: 60, y: 22, w: 180, h: 118, k: 3, stroke: 2.4, cut: true, labels, labelSize: 9, leafDot: 0, axis: true })}${txt(24, 80, 'height (distance)', { size: 8.5, cls: 'art-mut', rot: -90, anchor: 'middle' })}${arrow(292, 60, 258, 44)}${txt(296, 64, 'node = a merge', { size: 8, cls: 'art-mut' })}${txt(150, 170, 'leaves = observations', { size: 8.5, anchor: 'middle', cls: 'art-mut' })}${txt(246, 100, 'cut → k = 3', { size: 8.5, fill: '#d64a6a', bold: true })}${txt(150, 184, 'branch length ∝ dissimilarity at which groups join', { size: 8, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 'kmeans': { const r = rng(75); const base = blob(r, 30, 30, 8, 8).concat(blob(r, 62, 26, 7, 8)).concat(blob(r, 46, 60, 8, 8)); const panel = (p, title, draw) => { const ox = 8 + p * 78; return `<rect x="${ox}" y="18" width="72" height="100" rx="6" class="art-card"/>${txt(ox + 36, 12, title, { size: 8.5, anchor: 'middle', bold: true })}<g transform="translate(${ox + 4},26)">${draw()}</g>`; }; const C0 = [[20, 50], [30, 20], [60, 55]]; const a1 = KM.assign(base, C0); const C1 = KM.update(base, a1.cluster, C0); const a2 = KM.assign(base, C1); const C2 = KM.update(base, a2.cluster, C1); const final = KM.run(base, 3, { rng: rng(3), nstart: 5 }); return `${V}${defs}${panel(0, '1 · start', () => pts(base, '#999', 2.4) + C0.map((c, i) => star(c[0], c[1], 5, CL[i])).join(''))}${panel(1, '2 · assign', () => base.map((p, i) => `<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="2.4" fill="${CL[a1.cluster[i]]}"/>`).join('') + C0.map((c, i) => star(c[0], c[1], 5, CL[i])).join(''))}${panel(2, '3 · move', () => base.map((p, i) => `<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="2.4" fill="${CL[a1.cluster[i]]}"/>`).join('') + C0.map((c, i) => `<line x1="${c[0]}" y1="${c[1]}" x2="${C1[i][0].toFixed(1)}" y2="${C1[i][1].toFixed(1)}" stroke="${CL[i]}" stroke-width="1.4" stroke-dasharray="2 2"/>`).join('') + C1.map((c, i) => star(c[0], c[1], 5, CL[i])).join(''))}${panel(3, '4 · repeat', () => base.map((p, i) => `<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="2.4" fill="${CL[final.cluster[i]]}"/>`).join('') + final.centers.map((c, i) => star(c[0], c[1], 5, CL[i])).join(''))}${txt(160, 140, 'objective: minimise the total within-cluster sum of squares', { size: 8.5, anchor: 'middle', cls: 'art-mut' })}${txt(160, 156, 'WSS = Σₖ Σ_{i∈Cₖ} ‖xᵢ − μₖ‖²', { size: 9, anchor: 'middle', bold: true })}${txt(160, 176, 'result depends on the start → run many starts (nstart) or use k-means++', { size: 8, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 'optimalk': { const panel = (p, title, ys, best, yl, err) => { const ox = 10 + p * 104, sx = i => ox + 14 + i * 12, sy = v => 120 - v * 90; let g = `<rect x="${ox}" y="8" width="98" height="130" rx="6" class="art-card"/>${txt(ox + 49, 22, title, { size: 8.5, anchor: 'middle', bold: true })}${axes(ox + 10, 30, 84, 92, { xl: 'k', yl, size: 7 })}`; if (err) ys.forEach((v, i) => { g += `<line x1="${sx(i)}" x2="${sx(i)}" y1="${sy(v + 0.06)}" y2="${sy(v - 0.06)}" stroke="${CL[0]}" stroke-width="1"/>`; }); g += `<path d="${ys.map((v, i) => (i ? 'L' : 'M') + sx(i) + ',' + sy(v).toFixed(1)).join(' ')}" fill="none" stroke="${CL[0]}" stroke-width="1.8"/>`; ys.forEach((v, i) => { g += `<circle cx="${sx(i)}" cy="${sy(v).toFixed(1)}" r="2.6" fill="${i === best ? CL[1] : CL[0]}"/>`; }); g += `<line x1="${sx(best)}" x2="${sx(best)}" y1="32" y2="122" stroke="${CL[1]}" stroke-dasharray="3 2"/>${txt(sx(best) + 4, 40, 'k=' + (best + 1), { size: 8, bold: true, fill: CL[1] })}`; return g; }; return `${V}${panel(0, 'Elbow (WSS)', [1, 0.55, 0.3, 0.24, 0.2, 0.17, 0.15], 2, 'total within SS')}${panel(1, 'Average silhouette', [0.0, 0.62, 0.78, 0.7, 0.6, 0.55, 0.5], 2, 'mean s(i)')}${panel(2, 'Gap statistic', [0.2, 0.45, 0.75, 0.72, 0.7, 0.66, 0.6], 2, 'gap(k)', true)}${txt(160, 158, 'three voices, one decision: choose the k most criteria agree on,', { size: 8.5, anchor: 'middle', cls: 'art-mut' })}${txt(160, 172, 'then confirm that the clusters are interpretable', { size: 8.5, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 'silhouette': { const r = rng(76); const A = blob(r, 90, 90, 18, 14), B = blob(r, 230, 80, 18, 14); const i = A[4]; return `${V}${defs}${hullPath(A, CL[0], 10)}${hullPath(B, CL[1], 10)}${pts(A, CL[0], 3)}${pts(B, CL[1], 3)}${A.map(p => p === i ? '' : `<line x1="${i[0]}" y1="${i[1]}" x2="${p[0]}" y2="${p[1]}" stroke="${CL[0]}" stroke-width="0.7" opacity="0.5"/>`).join('')}${B.slice(0, 6).map(p => `<line x1="${i[0]}" y1="${i[1]}" x2="${p[0]}" y2="${p[1]}" stroke="${CL[1]}" stroke-width="0.7" opacity="0.5"/>`).join('')}<circle cx="${i[0]}" cy="${i[1]}" r="5.5" fill="#fff" stroke="${CL[3]}" stroke-width="2.2"/>${txt(i[0], i[1] - 10, 'i', { size: 11, anchor: 'middle', bold: true, fill: CL[3] })}${txt(60, 150, 'a(i) = mean distance to own cluster', { size: 9, fill: CL[0], bold: true })}${txt(60, 165, 'b(i) = mean distance to the nearest other cluster', { size: 9, fill: CL[1], bold: true })}${txt(60, 182, 's(i) = (b − a) / max(a, b)   ∈ [−1, 1]', { size: 9.5, bold: true })}</svg>`; }
    case 'dbscan': { const r = rng(77); const core = blob(r, 120, 90, 22, 30); const border = [[160, 60], [80, 120], [150, 130]]; const noise = [[40, 30], [270, 40], [260, 150], [30, 160]]; const eps = 22; return `${V}${core.slice(0, 3).map(p => `<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="${eps}" fill="${CL[0]}" opacity="0.08" stroke="${CL[0]}" stroke-width="0.8" stroke-dasharray="3 2"/>`).join('')}${pts(core, CL[0], 3.4)}${border.map(p => `<circle cx="${p[0]}" cy="${p[1]}" r="3.6" fill="${CL[1]}" stroke="#fff"/>`).join('')}${noise.map(p => `<path d="M${p[0] - 4},${p[1] - 4} L${p[0] + 4},${p[1] + 4} M${p[0] - 4},${p[1] + 4} L${p[0] + 4},${p[1] - 4}" stroke="#888" stroke-width="2"/>`).join('')}${txt(210, 96, '● core: ≥ minPts within ε', { size: 8.5, fill: CL[0], bold: true })}${txt(210, 110, '● border: near a core point', { size: 8.5, fill: CL[1], bold: true })}${txt(210, 124, '✕ noise: neither', { size: 8.5, fill: '#777', bold: true })}${txt(160, 172, 'finds arbitrary shapes, no k needed, flags outliers', { size: 8.5, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 'tanglegram': { const P = demoPoints(78, [[0, 0], [20, 2], [10, 18]], 4, 4); const D = HC.dist(P); const h1 = HC.agglomerate(D, 'ward.D2'), h2 = HC.agglomerate(D, 'single'); const n = h1.n, L1 = HC.layout(h1), L2 = HC.layout(h2); const cl = HC.cutree(h1, 3); let lines = ''; let cross = 0; for (let i = 0; i < n; i++) { const y1 = 20 + (L1.leafX[i] + 0.5) / n * 130, y2 = 20 + (L2.leafX[i] + 0.5) / n * 130; lines += `<line x1="118" y1="${y1.toFixed(1)}" x2="202" y2="${y2.toFixed(1)}" stroke="${CL[cl[i] - 1]}" stroke-width="1.6" opacity="0.85"/>`; } for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) if ((L1.leafX[i] - L1.leafX[j]) * (L2.leafX[i] - L2.leafX[j]) < 0) cross++; return `${V}${Art.dendro(h1, { orient: 'hl', x: 14, y: 20, w: 100, h: 130, k: 3, stroke: 2 })}${Art.dendro(h2, { orient: 'h', x: 206, y: 20, w: 100, h: 130, k: 3, stroke: 2 })}${lines}${txt(64, 14, 'Ward.D2', { size: 9, anchor: 'middle', bold: true })}${txt(256, 14, 'single', { size: 9, anchor: 'middle', bold: true })}${txt(160, 172, `crossings = ${cross} · cophenetic r(ward, single) = ${HC.copheneticCor(HC.cophenetic(h1), h2).toFixed(2)}`, { size: 8.5, anchor: 'middle', cls: 'art-mut' })}${txt(160, 185, 'same objects, two linkage rules: how much do the trees agree?', { size: 8, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 'families': { return `${V}${defs}<rect x="110" y="8" width="100" height="26" rx="8" fill="${CL[0]}"/>${txt(160, 25, 'CLUSTERING', { size: 10, anchor: 'middle', bold: true, fill: '#fff', ls: 1 })}${[[40, 'Hierarchical', 'tree of merges', CL[0]], [120, 'Partitioning', 'k groups, centres', CL[1]], [200, 'Density', 'dense regions', CL[2]], [280, 'Model-based', 'mixtures', CL[3]]].map(([x, t, s, c]) => `${arrow(160, 34, x, 62, '#999', 1)}<rect x="${x - 36}" y="64" width="72" height="40" rx="7" fill="${c}" opacity="0.14" stroke="${c}"/>${txt(x, 80, t, { size: 8.5, anchor: 'middle', bold: true, fill: c })}${txt(x, 94, s, { size: 7.5, anchor: 'middle', cls: 'art-mut' })}`).join('')}${txt(40, 122, 'agglomerative', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}${txt(40, 133, 'divisive (DIANA)', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}${txt(120, 122, 'k-means, PAM,', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}${txt(120, 133, 'CLARA, fuzzy', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}${txt(200, 122, 'DBSCAN', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}${txt(200, 133, 'HDBSCAN*', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}${txt(280, 122, 'Gaussian mixtures', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}${txt(280, 133, '(EM + BIC)', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}<rect x="60" y="150" width="200" height="28" rx="7" fill="${CL[5]}" opacity="0.14" stroke="${CL[5]}"/>${txt(160, 162, 'Hybrids: hierarchical k-means, HCPC (PCA + tree + k-means)', { size: 7.5, anchor: 'middle', fill: CL[5], bold: true })}${txt(160, 173, 'Fuzzy: each object gets membership degrees, not a hard label', { size: 7.5, anchor: 'middle', fill: CL[5] })}</svg>`; }
    case 'hopkins': { const r = rng(79); const U = []; for (let i = 0; i < 60; i++) U.push([20 + r() * 120, 20 + r() * 130]); const C = blob(r, 210, 60, 12, 20).concat(blob(r, 275, 120, 12, 20)).concat(blob(r, 205, 135, 10, 20)); return `${V}${defs}<rect x="12" y="12" width="136" height="146" rx="6" class="art-card"/><rect x="172" y="12" width="136" height="146" rx="6" class="art-card"/>${pts(U, '#9a9a9a', 2.6)}${pts(C, CL[0], 2.6)}${txt(80, 172, 'uniform: Hopkins H ≈ 0.5', { size: 8.5, anchor: 'middle', bold: true, fill: '#777' })}${txt(240, 172, 'clustered: H ≈ 0.85–0.99', { size: 8.5, anchor: 'middle', bold: true, fill: CL[0] })}${txt(160, 186, 'any algorithm will still return clusters from the left panel — that is the danger', { size: 7.5, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    case 'shapes': { const r = rng(80); const moon1 = [], moon2 = []; for (let i = 0; i < 26; i++) { const a = Math.PI * i / 25; moon1.push([70 + 40 * Math.cos(a) + randn(r) * 3, 80 - 30 * Math.sin(a) + randn(r) * 3]); moon2.push([110 + 40 * Math.cos(a + Math.PI) + randn(r) * 3, 90 - 30 * Math.sin(a + Math.PI) + randn(r) * 3]); } const ring = [], cen = blob(r, 240, 90, 7, 16); for (let i = 0; i < 34; i++) { const a = i / 34 * 2 * Math.PI; ring.push([240 + 46 * Math.cos(a) + randn(r) * 3, 90 + 46 * Math.sin(a) + randn(r) * 3]); } const km1 = KM.run(moon1.concat(moon2), 2, { rng: rng(1), nstart: 5 }), all2 = ring.concat(cen), km2 = KM.run(all2, 2, { rng: rng(2), nstart: 5 }); return `${V}${moon1.concat(moon2).map((p, i) => `<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="3" fill="${CL[km1.cluster[i]]}"/>`).join('')}${all2.map((p, i) => `<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="3" fill="${CL[km2.cluster[i]]}"/>`).join('')}${txt(90, 160, 'two moons · k-means splits them wrongly', { size: 8.5, anchor: 'middle', bold: true, fill: CL[3] })}${txt(240, 160, 'ring + core · also wrong', { size: 8.5, anchor: 'middle', bold: true, fill: CL[3] })}${txt(160, 180, 'single linkage, DBSCAN or spectral clustering recover these shapes', { size: 8.5, anchor: 'middle', cls: 'art-mut' })}</svg>`; }
    default: return `${V}</svg>`;
  }
};

Art.upload = () => `<svg viewBox="0 0 52 52" xmlns="http://www.w3.org/2000/svg"><circle cx="26" cy="26" r="24" class="art-p" opacity="0.15"/><path d="M26 36 V16 M17 25 l9 -9 l9 9" stroke="#4f46a5" stroke-width="3.2" fill="none" stroke-linecap="round" stroke-linejoin="round"/><path d="M15 38 h22" stroke="#4f46a5" stroke-width="3.2" stroke-linecap="round"/></svg>`;
Art.soon = () => { const { hc } = demoTree(99, [[0, 0], [20, 3], [10, 18]], 3, 'average', 4); return `<svg viewBox="0 0 220 130" xmlns="http://www.w3.org/2000/svg">${Art.dendro(hc, { x: 30, y: 30, w: 160, h: 70, k: 1, stroke: 2, neutral: '#b0b0c4', leafDot: 2.5, colors: ['#b0b0c4'] })}${txt(110, 20, 'growing…', { size: 12, anchor: 'middle', cls: 'art-mut' })}</svg>`; };

window.Art = Art; window.CL = CL;
